# Generated by Django 3.2.8 on 2023-08-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoasociados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='asociados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NoDocumento', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Direccion', models.CharField(max_length=100)),
                ('Beneficiario', models.CharField(max_length=100)),
                ('FechaIngreso', models.DateField(max_length=100)),
                ('TipoDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.tipoasociados')),
            ],
        ),
    ]
