# Generated by Django 3.2.8 on 2023-09-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ValorAporte', models.CharField(max_length=50)),
                ('MesAporte', models.CharField(max_length=100, verbose_name='Mes')),
                ('InteresAprote', models.CharField(max_length=100)),
                ('DevolAporte', models.CharField(max_length=100)),
                ('FechaAporte', models.DateField(max_length=100)),
                ('idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.asociados')),
                ('AnoAporte', models.CharField(max_length=100, verbose_name='Ano'))
           ],
        )
    ]
    
